In [1]:
from nba_api.stats.endpoints import teamgamelogs
import pandas as pd
import warnings
import time
warnings.simplefilter('ignore')

current_seasons=teamgamelogs.SeasonNullable.current_season
print(current_seasons)

2022-23

In [2]:
df=teamgamelogs.TeamGameLogs(season_nullable=current_seasons).get_data_frames()[0]

In [3]:
team_games=[]
for i,row in df.iterrows():
    team_game= f"{row['TEAM_ABBREVIATION']}_{row['GAME_ID']}"
    team_games.append(team_game)
df['team_games']=team_games
true_df=df.set_index('team_games')
true_df.index.name = 'team_game'
true_df

,SEASON_YEAR,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
team_game,,,,,,,,,,,,,,,,,,,,,
MIL_0022200548,2022-23,1610612749,MIL,Milwaukee Bucks,0022200548,2023-01-01T00:00:00,MIL vs. WAS,L,48.0,34,...,494,742,654,87,729,728,68,1095,1032,1050
SAC_0022200547,2022-23,1610612758,SAC,Sacramento Kings,0022200547,2023-01-01T00:00:00,SAC @ MEM,L,48.0,39,...,305,579,654,497,560,958,262,729,745,843
DEN_0022200549,2022-23,1610612743,DEN,Denver Nuggets,0022200549,2023-01-01T00:00:00,DEN vs. BOS,W,48.0,45,...,977,93,755,785,560,210,172,984,227,188
WAS_0022200548,2022-23,1610612764,WAS,Washington Wizards,0022200548,2023-01-01T00:00:00,WAS @ MIL,W,48.0,50,...,52,205,847,235,232,210,2,984,369,43
BOS_0022200549,2022-23,1610612738,BOS,Boston Celtics,0022200549,2023-01-01T00:00:00,BOS @ DEN,L,48.0,40,...,676,148,310,353,729,371,68,838,628,894
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ATL_0022200005,2022-23,1610612737,ATL,Atlanta Hawks,0022200005,2022-10-19T00:00:00,ATL vs. HOU,W,48.0,45,...,851,148,56,52,372,210,262,534,397,234
LAL_0022200002,2022-23,1610612747,LAL,Los Angeles Lakers,0022200002,2022-10-18T00:00:00,LAL @ GSW,L,48.0,40,...,252,660,1051,52,560,371,262,246,708,933
BOS_0022200001,2022-23,1610612738,BOS,Boston Celtics,0022200001,2022-10-18T00:00:00,BOS vs. PHI,W,48.0,46,...,948,579,148,353,729,210,854,119,145,257
PHI_0022200001,2022-23,1610612755,PHI,Philadelphia 76ers,0022200001,2022-10-18T00:00:00,PHI @ BOS,L,48.0,40,...,1059,1055,431,353,729,210,926,174,397,805
GSW_0022200002,2022-23,1610612744,GSW,Golden State Warriors,0022200002,2022-10-18T00:00:00,GSW vs. LAL,W,48.0,45,...,252,93,847,87,560,371,769,729,227,143

In [4]:
from oauth2client.service_account import ServiceAccountCredentials
from df2gspread import df2gspread as d2g

# The path of client_secret json file that you have downloaded
# path = '/nfs/home/data/'
 
scopes = ['https://www.googleapis.com/auth/spreadsheets', 
          "https://www.googleapis.com/auth/drive.file", 
          "https://www.googleapis.com/auth/drive"]
creds = ServiceAccountCredentials.from_json_keyfile_name('../gs_creds/client_secret.json', scopes)
def write_googlesheet(df,spreadsheet_key,sheet_title,starting_cell,overwrite):
    d2g.upload(df,
           spreadsheet_key,
           sheet_title,
           credentials=creds,
           col_names=True,
           row_names=True,
           start_cell = starting_cell,
           clean=overwrite)

In [5]:
true_df.columns

Index(['SEASON_YEAR', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS',
       'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'FGM_RANK',
       'FGA_RANK', 'FG_PCT_RANK', 'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK',
       'FTM_RANK', 'FTA_RANK', 'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK',
       'REB_RANK', 'AST_RANK', 'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK',
       'PF_RANK', 'PFD_RANK', 'PTS_RANK', 'PLUS_MINUS_RANK'],
      dtype='object')

In [6]:
write_googlesheet(true_df,'1WScIAA7DFu1VuhBjQ2H86KoAWG0K7Qvg6EpRpG6S68I','game_logs','A1',True)

In [7]:
true_df

,SEASON_YEAR,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
team_game,,,,,,,,,,,,,,,,,,,,,
MIL_0022200548,2022-23,1610612749,MIL,Milwaukee Bucks,0022200548,2023-01-01T00:00:00,MIL vs. WAS,L,48.0,34,...,494,742,654,87,729,728,68,1095,1032,1050
SAC_0022200547,2022-23,1610612758,SAC,Sacramento Kings,0022200547,2023-01-01T00:00:00,SAC @ MEM,L,48.0,39,...,305,579,654,497,560,958,262,729,745,843
DEN_0022200549,2022-23,1610612743,DEN,Denver Nuggets,0022200549,2023-01-01T00:00:00,DEN vs. BOS,W,48.0,45,...,977,93,755,785,560,210,172,984,227,188
WAS_0022200548,2022-23,1610612764,WAS,Washington Wizards,0022200548,2023-01-01T00:00:00,WAS @ MIL,W,48.0,50,...,52,205,847,235,232,210,2,984,369,43
BOS_0022200549,2022-23,1610612738,BOS,Boston Celtics,0022200549,2023-01-01T00:00:00,BOS @ DEN,L,48.0,40,...,676,148,310,353,729,371,68,838,628,894
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ATL_0022200005,2022-23,1610612737,ATL,Atlanta Hawks,0022200005,2022-10-19T00:00:00,ATL vs. HOU,W,48.0,45,...,851,148,56,52,372,210,262,534,397,234
LAL_0022200002,2022-23,1610612747,LAL,Los Angeles Lakers,0022200002,2022-10-18T00:00:00,LAL @ GSW,L,48.0,40,...,252,660,1051,52,560,371,262,246,708,933
BOS_0022200001,2022-23,1610612738,BOS,Boston Celtics,0022200001,2022-10-18T00:00:00,BOS vs. PHI,W,48.0,46,...,948,579,148,353,729,210,854,119,145,257
PHI_0022200001,2022-23,1610612755,PHI,Philadelphia 76ers,0022200001,2022-10-18T00:00:00,PHI @ BOS,L,48.0,40,...,1059,1055,431,353,729,210,926,174,397,805
GSW_0022200002,2022-23,1610612744,GSW,Golden State Warriors,0022200002,2022-10-18T00:00:00,GSW vs. LAL,W,48.0,45,...,252,93,847,87,560,371,769,729,227,143

####

In [8]:
from nba_api.stats import endpoints

In [9]:
player_game_logs=endpoints.playergamelogs.PlayerGameLogs(season_nullable=current_seasons).get_data_frames()[0]
player_game_logs.index.name= "index"

In [10]:
player_game_logs_real=player_game_logs[['SEASON_YEAR', 'PLAYER_ID', 'PLAYER_NAME', 'TEAM_ID','TEAM_ABBREVIATION', 'GAME_ID', 'GAME_DATE', 'MATCHUP',
       'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM',
       'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK',
       'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS', 'NBA_FANTASY_PTS']]
player_game_logs_real

,SEASON_YEAR,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,...,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,NBA_FANTASY_PTS
index,,,,,,,,,,,,,,,,,,,,,
0,2022-23,1628374,Lauri Markkanen,1610612762,UTA,0022200546,2022-12-31T00:00:00,UTA vs. MIA,L,36.033333,...,0,1,1,0,0,2,8,29,-1,47.8
1,2022-23,1628392,Isaiah Hartenstein,1610612752,NYK,0022200541,2022-12-31T00:00:00,NYK @ HOU,W,14.833333,...,1,1,1,0,1,3,1,0,-4,8.3
2,2022-23,201565,Derrick Rose,1610612752,NYK,0022200541,2022-12-31T00:00:00,NYK @ HOU,W,10.900000,...,1,0,0,0,0,0,0,4,-4,6.7
3,2022-23,1631102,TyTy Washington Jr.,1610612745,HOU,0022200541,2022-12-31T00:00:00,HOU vs. NYK,L,12.583333,...,0,0,0,0,0,3,2,1,-3,3.4
4,2022-23,1630227,Daishen Nix,1610612745,HOU,0022200541,2022-12-31T00:00:00,HOU vs. NYK,L,3.016667,...,1,1,0,0,0,0,0,0,-3,1.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11621,2022-23,202691,Klay Thompson,1610612744,GSW,0022200002,2022-10-18T00:00:00,GSW vs. LAL,W,19.650000,...,3,2,1,0,0,3,3,18,11,25.9
11622,2022-23,201566,Russell Westbrook,1610612747,LAL,0022200002,2022-10-18T00:00:00,LAL @ GSW,L,30.683333,...,3,4,1,0,1,1,3,19,-6,35.7
11623,2022-23,203952,Andrew Wiggins,1610612744,GSW,0022200002,2022-10-18T00:00:00,GSW vs. LAL,W,29.465000,...,4,1,1,1,0,5,1,20,25,38.2
11624,2022-23,203076,Anthony Davis,1610612747,LAL,0022200002,2022-10-18T00:00:00,LAL @ GSW,L,35.600000,...,0,3,4,1,1,2,7,27,-21,46.2
11625,2022-23,2544,LeBron James,1610612747,LAL,0022200002,2022-10-18T00:00:00,LAL @ GSW,L,35.200000,...,8,5,0,0,1,2,4,31,-10,56.0

In [11]:
write_googlesheet(player_game_logs_real,'1WScIAA7DFu1VuhBjQ2H86KoAWG0K7Qvg6EpRpG6S68I','player_logs','A1',True)

In [12]:
from nba_api.stats.static import teams
# get_teams returns a list of 30 dictionaries, each an NBA team.
nba_teams = teams.get_teams()
print('Number of teams fetched: {}'.format(len(nba_teams)))
nba_teams_real=pd.DataFrame(nba_teams)
write_googlesheet(nba_teams_real,'1WScIAA7DFu1VuhBjQ2H86KoAWG0K7Qvg6EpRpG6S68I','teams','A1',True)

Number of teams fetched: 30

In [13]:
team_ids=nba_teams_real['id']
team_ids

0     1610612737
1     1610612738
2     1610612739
3     1610612740
4     1610612741
5     1610612742
6     1610612743
7     1610612744
8     1610612745
9     1610612746
10    1610612747
11    1610612748
12    1610612749
13    1610612750
14    1610612751
15    1610612752
16    1610612753
17    1610612754
18    1610612755
19    1610612756
20    1610612757
21    1610612758
22    1610612759
23    1610612760
24    1610612761
25    1610612762
26    1610612763
27    1610612764
28    1610612765
29    1610612766
Name: id, dtype: int64

In [14]:
from nba_api.stats.static import players

In [15]:
nba_players = players.get_active_players()
print('Number of active players fetched: {}'.format(len(nba_players)))

Number of active players fetched: 582

In [16]:
nba_players_real=pd.DataFrame(nba_players)
nba_players_real

          id         full_name first_name  last_name  is_active
0    1630173  Precious Achiuwa   Precious    Achiuwa       True
1     203500      Steven Adams     Steven      Adams       True
2    1628389       Bam Adebayo        Bam    Adebayo       True
3    1630534      Ochai Agbaji      Ochai     Agbaji       True
4    1630583      Santi Aldama      Santi     Aldama       True
..       ...               ...        ...        ...        ...
577   201152    Thaddeus Young   Thaddeus      Young       True
578  1629027        Trae Young       Trae      Young       True
579  1630209    Omer Yurtseven       Omer  Yurtseven       True
580   203469       Cody Zeller       Cody     Zeller       True
581  1627826       Ivica Zubac      Ivica      Zubac       True

[582 rows x 5 columns]

In [17]:
player_ids=nba_players_real['id']
player_ids

0      1630173
1       203500
2      1628389
3      1630534
4      1630583
        ...
577     201152
578    1629027
579    1630209
580     203469
581    1627826
Name: id, Length: 582, dtype: int64

In [18]:
write_googlesheet(nba_players_real,'1WScIAA7DFu1VuhBjQ2H86KoAWG0K7Qvg6EpRpG6S68I','players','A1',True)

In [19]:
top_75_players=endpoints.leagueleaders.LeagueLeaders(season=current_seasons).get_data_frames()[0].iloc[:75]["PLAYER_ID"]
top_75_players

0     1629029
1     1628369
2      201142
3     1628983
4      203507
       ...
70    1626167
71    1627832
72     201572
73    1628370
74    1629018
Name: PLAYER_ID, Length: 75, dtype: int64

In [20]:
seasons=['2020-21','2021-22','2022-23']

In [21]:
# ls=[]
# dict={}
# for season in seasons:
#     for team in team_ids[:3]:
#         for player in top_75_players [:3]:
#             try:
#                 player_vs_team=endpoints.teamvsplayer.TeamVsPlayer(vs_player_id=player,team_id=team,opponent_team_id=team,season=season).vs_player_overall.get_data_frame()
#                 pvt_df=player_vs_team[['GROUP_VALUE', 'PLAYER_ID', 'GP', 'W_PCT',
#                        'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA',
#                        'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'BLKA',
#                        'PF', 'PFD', 'PTS', 'PLUS_MINUS', 'NBA_FANTASY_PTS']]
#                 pvt_df['team_id']=team
#                 pvt_df['season']=season
#                 ls.append(pvt_df)
#             except:
#                 print("Variable not found")

In [22]:
# ls=[]
# dict={}
# for season in seasons:
#     for team in team_ids:
#         for player in top_75_players:
#             try:
#                 player_vs_team=endpoints.teamvsplayer.TeamVsPlayer(vs_player_id=player,team_id=team,opponent_team_id=team,season=season,season_type_playoffs="Regular Season").vs_player_overall.get_data_frame()
#                 pvt_df=player_vs_team[['GROUP_VALUE', 'PLAYER_ID', 'GP', 'W_PCT',
#                        'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA',
#                        'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'BLKA',
#                        'PF', 'PFD', 'PTS', 'PLUS_MINUS', 'NBA_FANTASY_PTS']]
#                 pvt_df['team_id']=team
#                 pvt_df['season']=season
#                 ls.append(pvt_df)
#                 time.sleep(.600)
#             except:
#                 print(f"data for {player} against {team} in {season} not found")

In [23]:
top_75_ls=[]
for season in seasons:
    print(f"Starting to get data for {season}")
    for player in top_75_players:
        try:
            print(f"getting data for {player}")
            player_game_logs=endpoints.playergamelogs.PlayerGameLogs(season_nullable=season,player_id_nullable=player).get_data_frames()[0]
            player_game_logs.index.name= "initial_index"
            player_game_logs_real=player_game_logs[['SEASON_YEAR', 'PLAYER_ID', 'PLAYER_NAME', 'TEAM_ID','TEAM_ABBREVIATION', 'GAME_ID', 'GAME_DATE', 'MATCHUP',
           'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM',
           'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK',
           'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS', 'NBA_FANTASY_PTS']]
            top_75_ls.append(player_game_logs_real)
            time.sleep(1)
        except:
            print(f"No data for {player} in {season}")

Starting to get data for 2020-21
getting data for 1629029
getting data for 1628369
getting data for 201142
getting data for 1628983
getting data for 203507
getting data for 1627759
getting data for 201942
getting data for 1628378
getting data for 203954
getting data for 203944
getting data for 1630162
getting data for 1629027
getting data for 1628374
getting data for 203999
getting data for 1629630
getting data for 2544
getting data for 202711
getting data for 1628398
getting data for 1626164
getting data for 203903
getting data for 201939
getting data for 1630224
getting data for 204001
getting data for 1629673
getting data for 1628368
getting data for 1629014
getting data for 1630532
getting data for 1630169
getting data for 1629627
getting data for 203924
getting data for 203897
getting data for 1626162
getting data for 1628389
getting data for 1629628
getting data for 1627783
getting data for 1628973
getting data for 1629640
getting data for 203076
getting data for 202331
getting data for 202681
getting data for 1629645
getting data for 1627741
getting data for 1629636
getting data for 203081
getting data for 1631097
getting data for 1627749
getting data for 203468
getting data for 1627734
getting data for 1631094
getting data for 1629639
getting data for 1626174
getting data for 202696
getting data for 1628384
getting data for 1626156
getting data for 203915
getting data for 1629028
getting data for 1628969
getting data for 1628415
getting data for 202691
getting data for 1627736
getting data for 1630170
getting data for 203078
getting data for 1629023
getting data for 203932
getting data for 202699
getting data for 1626179
getting data for 1628989
getting data for 1631093
getting data for 1627750
getting data for 1630596
getting data for 1626167
getting data for 1627832
getting data for 201572
getting data for 1628370
getting data for 1629018
Starting to get data for 2021-22
getting data for 1629029
getting data for 1628369
getting data for 201142
getting data for 1628983
getting data for 203507
getting data for 1627759
getting data for 201942
getting data for 1628378
getting data for 203954
getting data for 203944
getting data for 1630162
getting data for 1629027
getting data for 1628374
getting data for 203999
getting data for 1629630
getting data for 2544
getting data for 202711
getting data for 1628398
getting data for 1626164
getting data for 203903
getting data for 201939
getting data for 1630224
getting data for 204001
getting data for 1629673
getting data for 1628368
getting data for 1629014
getting data for 1630532
getting data for 1630169
getting data for 1629627
getting data for 203924
getting data for 203897
getting data for 1626162
getting data for 1628389
getting data for 1629628
getting data for 1627783
getting data for 1628973
getting data for 1629640
getting data for 203076
getting data for 202331
getting data for 202681
getting data for 1629645
getting data for 1627741
getting data for 1629636
getting data for 203081
getting data for 1631097
getting data for 1627749
getting data for 203468
getting data for 1627734
getting data for 1631094
getting data for 1629639
getting data for 1626174
getting data for 202696
getting data for 1628384
getting data for 1626156
getting data for 203915
getting data for 1629028
getting data for 1628969
getting data for 1628415
getting data for 202691
getting data for 1627736
getting data for 1630170
getting data for 203078
getting data for 1629023
getting data for 203932
getting data for 202699
getting data for 1626179
getting data for 1628989
getting data for 1631093
getting data for 1627750
getting data for 1630596
getting data for 1626167
getting data for 1627832
getting data for 201572
getting data for 1628370
getting data for 1629018
Starting to get data for 2022-23
getting data for 1629029
getting data for 1628369
getting data for 201142
getting data for 1628983
getting data for 203507
getting data for 1627759
getting data for 201942
getting data for 1628378
getting data for 203954
getting data for 203944
getting data for 1630162
getting data for 1629027
getting data for 1628374
getting data for 203999
getting data for 1629630
getting data for 2544
getting data for 202711
getting data for 1628398
getting data for 1626164
getting data for 203903
getting data for 201939
getting data for 1630224
getting data for 204001
getting data for 1629673
getting data for 1628368
getting data for 1629014
getting data for 1630532
getting data for 1630169
getting data for 1629627
getting data for 203924
getting data for 203897
getting data for 1626162
getting data for 1628389
getting data for 1629628
getting data for 1627783
getting data for 1628973
getting data for 1629640
getting data for 203076
getting data for 202331
getting data for 202681
getting data for 1629645
getting data for 1627741
getting data for 1629636
getting data for 203081
getting data for 1631097
getting data for 1627749
getting data for 203468
getting data for 1627734
getting data for 1631094
getting data for 1629639
getting data for 1626174
getting data for 202696
getting data for 1628384
getting data for 1626156
getting data for 203915
getting data for 1629028
getting data for 1628969
getting data for 1628415
getting data for 202691
getting data for 1627736
getting data for 1630170
getting data for 203078
getting data for 1629023
getting data for 203932
getting data for 202699
getting data for 1626179
getting data for 1628989
getting data for 1631093
getting data for 1627750
getting data for 1630596
getting data for 1626167
getting data for 1627832
getting data for 201572
getting data for 1628370
getting data for 1629018

In [24]:
top_75=pd.concat(top_75_ls)
opponents=[]
home_or_away=[]
for i,row in top_75.iterrows():
    opponents.append(str(row['MATCHUP'].split(".")[-1].split("@")[-1]))
    if "@" in row['MATCHUP']:
        home_or_away.append("Away")
    else:
        home_or_away.append("Home")
        
top_75['opponents']=opponents
top_75['location']=home_or_away

In [25]:
top_75

,SEASON_YEAR,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,...,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,NBA_FANTASY_PTS,opponents,location
initial_index,,,,,,,,,,,,,,,,,,,,,
0,2020-21,1629029,Luka Doncic,1610612742,DAL,0022001071,2021-05-16T00:00:00,DAL @ MIN,L,20.738333,...,2,0,1,1,3,18,-15,36.2,MIN,Away
1,2020-21,1629029,Luka Doncic,1610612742,DAL,0022001057,2021-05-14T00:00:00,DAL vs. TOR,W,34.216667,...,0,1,0,4,5,20,-5,50.5,TOR,Home
2,2020-21,1629029,Luka Doncic,1610612742,DAL,0022000154,2021-05-12T00:00:00,DAL vs. NOP,W,31.266667,...,0,0,0,1,3,33,24,50.6,NOP,Home
3,2020-21,1629029,Luka Doncic,1610612742,DAL,0022001037,2021-05-11T00:00:00,DAL @ MEM,L,25.500000,...,0,0,0,1,3,12,-23,20.5,MEM,Away
4,2020-21,1629029,Luka Doncic,1610612742,DAL,0022001021,2021-05-09T00:00:00,DAL @ CLE,W,21.616667,...,2,0,0,2,4,15,4,33.5,CLE,Away
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24,2022-23,1629018,Gary Trent Jr.,1610612761,TOR,0022200059,2022-10-26T00:00:00,TOR vs. PHI,W,35.450000,...,2,0,0,1,0,27,2,31.0,PHI,Home
25,2022-23,1629018,Gary Trent Jr.,1610612761,TOR,0022200045,2022-10-24T00:00:00,TOR @ MIA,W,42.213333,...,1,0,0,1,1,18,5,24.2,MIA,Away
26,2022-23,1629018,Gary Trent Jr.,1610612761,TOR,0022200031,2022-10-22T00:00:00,TOR @ MIA,L,38.916667,...,2,1,0,3,4,23,-6,35.2,MIA,Away
27,2022-23,1629018,Gary Trent Jr.,1610612761,TOR,0022200021,2022-10-21T00:00:00,TOR @ BKN,L,35.966667,...,1,0,3,0,1,14,-9,18.2,BKN,Away
28,2022-23,1629018,Gary Trent Jr.,1610612761,TOR,0022200008,2022-10-19T00:00:00,TOR vs. CLE,W,36.983333,...,1,0,0,1,5,19,3,27.0,CLE,Home

In [26]:
write_googlesheet(top_75.reset_index(),'1WScIAA7DFu1VuhBjQ2H86KoAWG0K7Qvg6EpRpG6S68I','top_75_splits','A1',True)